### ISSUE TITLE
Changing connection - always reload plugins

### ISSUE THREAD

**Issue by rappen** [drivardxrm/Driv.XTB.PluginIdentityManager#1]
Do that automatically, please :)

---
- Deployment: Online
- DB Version: 9.2.24094.212
- Connection Controls Version: 1.2024.9.59
- XrmToolBox Version: 1.2024.9.69
- Tool Version: 1.2024.10.258

**Comment by drivardxrm** [comment]
Will do, thanks for the feedback ;)

**Comment by drivardxrm** [comment]
Fixed in v1.2024.10.259
